// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Sm_Disp

#ifndef _SM_DISP_UI_H
#define _SM_DISP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_GaugeFace;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui_ledDarkImage;
extern lv_obj_t *ui_ledRedImage;
extern lv_obj_t *ui_Needle;
extern lv_obj_t *ui_vacLabel;
extern lv_obj_t *ui_redBugImg;
extern lv_obj_t *ui_grnBugImg;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_small_gauge_scale_png);   // assets/Small_Gauge_Scale.png
LV_IMG_DECLARE( ui_img_dark_led_png);   // assets/Dark_LED.png
LV_IMG_DECLARE( ui_img_red_led_png);   // assets/Red_LED.png
LV_IMG_DECLARE( ui_img_small_gauge_needle_png);   // assets/Small_Gauge_Needle.png
LV_IMG_DECLARE( ui_img_red_bug__png);   // assets/red_bug_.png
LV_IMG_DECLARE( ui_img_grn_bug__png);   // assets/grn_bug_.png
LV_IMG_DECLARE( ui_img_45621010);   // assets/Red_Bug-17X26.png

// FONTS
LV_FONT_DECLARE( ui_font_courier_Bold);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
