// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Sm_Disp

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GaugeFace = lv_img_create(ui_Screen1);
lv_img_set_src(ui_GaugeFace, &ui_img_small_gauge_scale_png);
lv_obj_set_width( ui_GaugeFace, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GaugeFace, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GaugeFace, 0 );
lv_obj_set_y( ui_GaugeFace, -6 );
lv_obj_set_align( ui_GaugeFace, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_GaugeFace, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_GaugeFace, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spinner1 = lv_spinner_create(ui_Screen1,4000,90);
lv_obj_set_width( ui_Spinner1, 30);
lv_obj_set_height( ui_Spinner1, 30);
lv_obj_set_x( ui_Spinner1, 20 );
lv_obj_set_y( ui_Spinner1, 49 );
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_width(ui_Spinner1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_Spinner1, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_ledDarkImage = lv_img_create(ui_Screen1);
lv_img_set_src(ui_ledDarkImage, &ui_img_dark_led_png);
lv_obj_set_width( ui_ledDarkImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ledDarkImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ledDarkImage, 42 );
lv_obj_set_y( ui_ledDarkImage, 5 );
lv_obj_set_align( ui_ledDarkImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ledDarkImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ledDarkImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ledRedImage = lv_img_create(ui_Screen1);
lv_img_set_src(ui_ledRedImage, &ui_img_red_led_png);
lv_obj_set_width( ui_ledRedImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ledRedImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ledRedImage, 42 );
lv_obj_set_y( ui_ledRedImage, 5 );
lv_obj_set_align( ui_ledRedImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ledRedImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ledRedImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Needle = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Needle, &ui_img_small_gauge_needle_png);
lv_obj_set_width( ui_Needle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Needle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Needle, -32 );
lv_obj_set_y( ui_Needle, 35 );
lv_obj_set_align( ui_Needle, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Needle, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Needle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_Needle,78,15);

ui_vacLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_vacLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_vacLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_vacLabel, 0 );
lv_obj_set_y( ui_vacLabel, -24 );
lv_obj_set_align( ui_vacLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_vacLabel,"30.0");
lv_obj_set_style_text_color(ui_vacLabel, lv_color_hex(0xBEDBBE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_vacLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_vacLabel, -2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_vacLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_vacLabel, &ui_font_courier_Bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_vacLabel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_vacLabel, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_vacLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_redBugImg = lv_img_create(ui_Screen1);
lv_img_set_src(ui_redBugImg, &ui_img_red_bug__png);
lv_obj_set_width( ui_redBugImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_redBugImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_redBugImg, 0 );
lv_obj_set_y( ui_redBugImg, -107 );
lv_obj_set_align( ui_redBugImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_redBugImg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_redBugImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_redBugImg,8,119);
lv_img_set_angle(ui_redBugImg,-450);

ui_grnBugImg = lv_img_create(ui_Screen1);
lv_img_set_src(ui_grnBugImg, &ui_img_grn_bug__png);
lv_obj_set_width( ui_grnBugImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_grnBugImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_grnBugImg, 0 );
lv_obj_set_y( ui_grnBugImg, -107 );
lv_obj_set_align( ui_grnBugImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_grnBugImg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_grnBugImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_grnBugImg,8,119);
lv_img_set_angle(ui_grnBugImg,-900);


}
